export const SET_USER = "SET_USER";
export const GET_ERRORS = "GET_ERRORS";
export const RESET_ERRORS = "RESET_ERRORS";
export const RESET_USER = "RESET_USER";
export const REMOVE_ACCESS = "REMOVE_ACCESS";
export const LOGOUT = "LOGOUT";
export const SET_IS_FETCHING = "SET_IS_FETCHING";
export const LIST_PAGE_REQUEST_SEND = "LIST_PAGE_REQUEST_SEND";
export const LIST_PAGE_REQUEST_ERROR = "LIST_PAGE_REQUEST_ERROR";
export const LIST_PAGE_REQUEST_SUCCESS = "LIST_PAGE_REQUEST_SUCCESS";
export const CREATE_PAGE_REQUEST = "CREATE_PAGE_REQUEST";
export const CREATE_PAGE_ERROR = "CREATE_PAGE_ERROR";
export const CREATE_PAGE_SUCCESS = "CREATE_PAGE_SUCCESS";
export const ADD_EMAIL_VERIFICATION_TOKEN = "ADD_EMAIL_VERIFICATION_TOKEN";
export const REMOVE_EMAIL_VERIFICATION_TOKEN =
  "REMOVE_EMAIL_VERIFICATION_TOKEN";
export const ADD_ACCESS_TOKEN_USER = "ADD_ACCESS_TOKEN_USER";
